# Generated by Django 4.1 on 2023-09-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_dispatch_detail_party_details_sales_invoice_sales_voucher_stock_item_allocation_sales_voucher_stock_'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_id', models.IntegerField(null=True)),
                ('sup_inv_no', models.CharField(max_length=255, null=True)),
                ('vouch_date', models.DateField(blank=True, null=True)),
                ('particulars', models.CharField(max_length=255, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('narration', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_id', models.IntegerField(null=True)),
                ('particular', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_amount', models.IntegerField(null=True)),
                ('debit_amount', models.IntegerField(null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('purchase_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchase_voucher')),
            ],
        ),
    ]
