# Generated by Django 4.1 on 2023-09-06 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_contra_particulars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contra_particulars',
            name='contra_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.contra_voucher'),
        ),
    ]
