# Generated by Django 4.1 on 2023-09-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_contra_particulars_contra_voucher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='purchase_voucher',
            new_name='purchase_vouchers',
        ),
    ]
