# Generated by Django 4.1 on 2023-09-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_purchase_voucher_purchase_vouchers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='purchase_vouchers',
            new_name='purchase_voucher',
        ),
    ]
