# Generated by Django 4.1 on 2023-09-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_purchase_vouchers_purchase_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transactions',
            name='contra_particular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank_transactions',
            name='contra_voucher',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
